CREATE TABLE students (
  id BIGSERIAL PRIMARY KEY,
  full_name VARCHAR(200) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  year INTEGER NOT NULL CHECK (year BETWEEN 1 AND 6),
  status VARCHAR(30) NOT NULL
);
CREATE TABLE teachers (
  id BIGSERIAL PRIMARY KEY,
  full_name VARCHAR(200) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  department VARCHAR(150) NOT NULL
);
CREATE TABLE courses (
  id BIGSERIAL PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  credits INTEGER NOT NULL CHECK (credits BETWEEN 1 AND 30),
  semester VARCHAR(50) NOT NULL,
  teacher_id BIGINT NOT NULL REFERENCES teachers(id)
);
CREATE TABLE enrollments (
  id BIGSERIAL PRIMARY KEY,
  student_id BIGINT NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  paid BOOLEAN NOT NULL DEFAULT FALSE,
  grade DOUBLE PRECISION CHECK (grade IS NULL OR (grade >= 0 AND grade <= 100)),
  enrolled_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_student_course UNIQUE(student_id, course_id)
);
